# Generated by Django 4.2.7 on 2025-07-06 22:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, numbers and underscores only.', max_length=150, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_username', message='Username can only contain letters, numbers, and underscores.', regex='^[a-zA-Z0-9_]+$')]),
        ),
    ]
