# Generated by Django 4.2.7 on 2025-07-07 03:24

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DayPatternThrough',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pattern_index', models.IntegerField()),
            ],
            options={
                'ordering': ['pattern_index'],
            },
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ExercisePattern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Muscle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='SplitDayThrough',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_index', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='WorkoutDayTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('patterns', models.ManyToManyField(related_name='day_templates', through='training.DayPatternThrough', to='training.exercisepattern')),
            ],
        ),
        migrations.CreateModel(
            name='WorkoutSplitTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('days_per_week', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(7)])),
                ('workouts', models.ManyToManyField(through='training.SplitDayThrough', to='training.workoutdaytemplate')),
            ],
        ),
        migrations.CreateModel(
            name='UserPreferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('days_per_week', models.IntegerField(default=2, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(7)])),
                ('training_age', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('volume', models.CharField(choices=[('low', 'Low'), ('moderate', 'Moderate'), ('high', 'High')], max_length=50)),
                ('priority_muscles', models.JSONField(blank=True, default=list, null=True)),
                ('bodyweight_exercises', models.CharField(choices=[('bodyweight', 'Bodyweight'), ('weighted', 'Weighted'), ('absent', 'Absent')], max_length=50)),
                ('equipment', models.JSONField(default=list)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='splitdaythrough',
            name='day_template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='training.workoutdaytemplate'),
        ),
        migrations.AddField(
            model_name='splitdaythrough',
            name='split',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='training.workoutsplittemplate'),
        ),
        migrations.AddField(
            model_name='exercisepattern',
            name='target_muscles',
            field=models.ManyToManyField(to='training.muscle'),
        ),
        migrations.CreateModel(
            name='ExerciseMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('tags', models.JSONField(default=list)),
                ('equipment', models.ManyToManyField(to='training.equipment')),
                ('pattern', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='training.exercisepattern')),
            ],
        ),
        migrations.AddField(
            model_name='daypatternthrough',
            name='day_template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='training.workoutdaytemplate'),
        ),
        migrations.AddField(
            model_name='daypatternthrough',
            name='pattern',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='training.exercisepattern'),
        ),
    ]
