# Generated by Django 4.2.7 on 2025-07-10 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercisepattern',
            name='target_muscles',
        ),
        migrations.AddField(
            model_name='exercisepattern',
            name='primary_muscles',
            field=models.ManyToManyField(related_name='primary_for', to='training.muscle'),
        ),
        migrations.AddField(
            model_name='exercisepattern',
            name='secondary_muscles',
            field=models.ManyToManyField(related_name='secondary_for', to='training.muscle'),
        ),
    ]
