# Generated by Django 4.2.7 on 2025-07-07 03:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercisemovement',
            name='tags',
        ),
    ]
