# Generated by Django 4.2.7 on 2025-07-10 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0002_remove_exercisepattern_target_muscles_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercisemovement',
            name='form_image',
            field=models.ImageField(blank=True, null=True, upload_to='exercise_form_images'),
        ),
        migrations.AddField(
            model_name='workoutdaytemplate',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
