# Generated by Django 4.2.7 on 2025-07-07 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0002_remove_exercisemovement_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userpreferences',
            name='equipment',
        ),
        migrations.RemoveField(
            model_name='userpreferences',
            name='priority_muscles',
        ),
        migrations.AddField(
            model_name='userpreferences',
            name='equipment',
            field=models.ManyToManyField(to='training.equipment'),
        ),
        migrations.AddField(
            model_name='userpreferences',
            name='priority_muscles',
            field=models.ManyToManyField(to='training.muscle'),
        ),
    ]
