# Generated by Django 4.2.7 on 2025-07-07 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0003_remove_userpreferences_equipment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercisemovement',
            name='type',
            field=models.CharField(choices=[('compound', 'Compound'), ('isolation', 'Isolation')], default='compound', max_length=100),
        ),
    ]
