# Generated by Django 4.2.7 on 2025-07-08 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0005_workoutplan_workoutday_plannedexercise'),
    ]

    operations = [
        migrations.AddField(
            model_name='daypatternthrough',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='splitdaythrough',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
