# Generated by Django 4.2.7 on 2025-07-08 04:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0006_daypatternthrough_name_splitdaythrough_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='splitdaythrough',
            options={'ordering': ['day_index']},
        ),
        migrations.RemoveField(
            model_name='daypatternthrough',
            name='name',
        ),
        migrations.RemoveField(
            model_name='splitdaythrough',
            name='name',
        ),
    ]
