# Generated by Django 4.2.7 on 2025-07-10 01:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0008_exerciselog_workoutlog_setlog_exerciselog_workout'),
    ]

    operations = [
        migrations.AddField(
            model_name='workoutlog',
            name='workout_day',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='training.workoutday'),
        ),
    ]
